export enum ErrorType {
  DUPLICATE = 'DUPLICATE',
  UNKNOWN = 'UNKNOWN',
  INVALID = 'INVALID',
  NOTFOUND = 'NOTFOUND',
  FORBIDDEN = 'FORBIDDEN',
  UNAUTHORIZED = 'UNAUTHORIZED',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
}
